version: '3'
services:
    client:
        image: client
        stdin_open: true
        ports:
            - '3000:3000'
        networks:
            - url-shortner-app
    server:
        image: server
        environment:
            - NODE_ENV=production
        stdin_open: true
        ports:
            - '5000:5000'
        networks:
            - url-shortner-app
        depends_on:
            - mongo
    mongo:
        image: mongo:3.6.19-xenial
        ports:
            - '27017:27017'
        networks:
            - url-shortner-app
        volumes:
            - mongo-data:/data/db
networks:
    url-shortner-app:
        driver: bridge
volumes:
    mongo-data:
        driver: local
